spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drcode?useUnicode=true&characterEncoding=utf8
    username: drcode
    password: qwer1234
   
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true
  
  thymeleaf:
    cache: false
server:
  port: 8015
